export const NOTIFICATION_TYPE = {
  CONVERSATION: 'conversation',
  USER: 'user',
  LIKE: 'like',
  LIKE_COMMENT: 'like_comment',
  MATCHED: 'matched',
  FOOTPRINT: 'footprint',
  WITHDRAW: 'withdraw',
  AGE_VERIFY: 'age_verify',
  POINT_CHANGE: 'point_change',
  TWEET: 'tweet',
  COMMUNITY: 'community',
  NEW_COMMENT: 'new_community_comment',
  NEW_COMMENT_FOLLOWED: 'new_community_comment_followed',
  NEW_TWEET_COMMUNITY: 'new_tweet_community',
  APPROVE_COMMUNITY_REQUEST: 'approve_community_request',
  COMMUNITY_ADMIN_ASSIGN: 'community_admin_assign',
  REPLY_COMMENT: 'reply_comment',
  LIKE_REPLY_COMMENT: 'like_reply_comment',
  LIKE_REPLY_TWEET_COMMENT: 'like_reply_tweet_comment',
  LIKE_TWEET_COMMENT: 'like_tweet_comment',
  TWEET_REPLY_COMMENT: 'tweet_reply_comment',
  TWEET_NEW_COMMENT: 'tweet_new_comment',
  MESSAGE: 'message',
  REQUEST_JOIN_GROUP: 'request_join_group',
  GROUP_ACTIVITY: 'group_activity',
  NEW_MESSAGE: 'new_message'
};
